version: '3.8'

services:
  nest-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: saraaa
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
